version: '3.8'

services:

  panda:
    build:
       context: .
       dockerfile: Dockerfile
    image: panda:latest
    restart: always
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      PORT: "8888"
    ports:
      - "8888:8888"
    depends_on:
      - mongo
      - seed

  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    image: panda:latest
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    command: ["python3", "-u", "src/db/seed.py"]

volumes:
  mongo_data: